issuesOpened: >
  If this is a question about Moonlight or you need help troubleshooting a streaming problem, please use the help channels on our [Discord server](https://discord.gg/MySTSdq) instead of GitHub issues. There are many more people available on Discord to help you and answer your questions.

  This issue tracker should only be used for specific bugs or feature requests.

  Thank you, and happy streaming!