language: cpp

git:
  depth: 1

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      sudo: required
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt597-xenial'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
          packages:
            - qt59base
            - qt59quickcontrols2
            - qt59svg
            - libesd0-dev
            - libgl-dev
            - libegl1-mesa-dev
            - libxkbcommon-dev
            - wayland-protocols
            - libopus-dev
            - libavcodec-dev
            - libavutil-dev
            - libva-dev
            - libvdpau-dev

install:
    - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt5'
    - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt5'
    - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then export SDL2_VER=2.0.9 && wget https://www.libsdl.org/release/SDL2-$SDL2_VER.tar.gz && tar -xvf SDL2-$SDL2_VER.tar.gz && cd SDL2-$SDL2_VER && ./configure && make && sudo make install && cd ..; fi
    - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then export SDL2_TTF_VER=2.0.15 && wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-$SDL2_TTF_VER.tar.gz && tar -xvf SDL2_ttf-$SDL2_TTF_VER.tar.gz && cd SDL2_ttf-$SDL2_TTF_VER && ./configure && make && sudo make install && cd ..; fi

before_script:
    - '[ "$TRAVIS_OS_NAME" != "linux" ] || source /opt/qt59/bin/qt59-env.sh'
    - qmake -v
    - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
    - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
    - '[ "$TRAVIS_OS_NAME" != osx ]                          || export QMAKESPEC=macx-clang'

script:
    - qmake moonlight-qt.pro -spec $QMAKESPEC
    - make debug
    - make release
