name: Test Simple Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Test step
      run: |
        echo "Hello from GitHub Actions!"
        echo "Current directory: $(pwd)"
        echo "Files:"
        ls -la